[package]
name = "easy-sq"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.24"
parking_lot = "0.12"
rodio = { version = "0.17" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
